/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author User
 */
public class modifySalesOrder extends javax.swing.JFrame {

    /**
     * Creates new form modifySalesOrder
     */
    public modifySalesOrder() {
        initComponents();
        tableInitialize();
    }
    public static String[] row;
    public String personalID;
    
    public modifySalesOrder(String[] row){
        initComponents();
        modifySalesOrder.row = row;
        SalesPerson sp = new SalesPerson(row[0],row[1],row[3],row[6],row[5],row[4],row[2]);
        personalID = sp.getID();
        setLocationRelativeTo(null);
        tableInitialize();
        updateSOIDbox(personalID);
        
        cbSOID.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String selectedSOID = (String)cbSOID.getSelectedItem();
                    if(selectedSOID != null && !selectedSOID.isEmpty()){
                        updateTable(selectedSOID);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(modifySalesOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }
    
    private void tableInitialize(){
        orderTable.getColumnModel().getColumn(0).setPreferredWidth(200); // Product
        orderTable.getColumnModel().getColumn(1).setPreferredWidth(80);  // Price
        orderTable.getColumnModel().getColumn(2).setPreferredWidth(80);  // Quantity
    }
    
    private void updateSOIDbox(String personalID){
        Set<String> uniqueSOIDs = new HashSet<>();
        
        try{
            FileReader fr = new FileReader("SalesOrder.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String regex = Pattern.quote(personalID) + "(\\d+)";
                Pattern pattern = Pattern.compile(regex);
                Matcher matcher = pattern.matcher(line);

                if (matcher.find()) {
                    String currentSalesOrderID = matcher.group(0);
                    uniqueSOIDs.add(currentSalesOrderID);
                }
            }
        } catch (IOException ex) {

        }
        cbSOID.addItem("");
        for (String uniqueSOID : uniqueSOIDs) {
            cbSOID.addItem(uniqueSOID);
        }
    }
    
    private void updateTable(String selectedSOID) throws FileNotFoundException, IOException{
        FileReader fr = new FileReader("SalesOrder.txt");
        BufferedReader br = new BufferedReader(fr);
        String line;
        while((line = br.readLine()) != null){
            if(line.contains(selectedSOID)){
                System.out.println(line);
            }
            String[] allProducts = line.split(",");
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbSOID = new javax.swing.JLabel();
        cbSOID = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lbProduct = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lbPrice = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbQuantity = new javax.swing.JLabel();
        spinQuantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        lbTitle = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modify Sales Order");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout());

        lbSOID.setBackground(new java.awt.Color(204, 255, 255));
        lbSOID.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbSOID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSOID.setText("Sales Order ID:");
        jPanel3.add(lbSOID);

        cbSOID.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel3.add(cbSOID);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout());

        lbProduct.setBackground(new java.awt.Color(204, 255, 255));
        lbProduct.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProduct.setText("Product:");
        jPanel4.add(lbProduct);

        cbProduct.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel4.add(cbProduct);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout());

        lbPrice.setBackground(new java.awt.Color(204, 255, 255));
        lbPrice.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("Price:");
        jPanel5.add(lbPrice);

        tfPrice.setEditable(false);
        tfPrice.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        tfPrice.setFocusable(false);
        jPanel5.add(tfPrice);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout());

        lbQuantity.setBackground(new java.awt.Color(204, 255, 255));
        lbQuantity.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuantity.setText("Quantity:");
        jPanel6.add(lbQuantity);

        spinQuantity.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        spinQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel6.add(spinQuantity);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 390, 350));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 120, 530, -1));

        lbTitle.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        lbTitle.setText("Modify Sales Order");
        jPanel1.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 400, 60));

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton2.setText("Add New");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 100, 50));

        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setMaximumSize(new java.awt.Dimension(80, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(80, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(80, 23));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 90, 50));

        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton4.setText("Edit");
        jButton4.setMaximumSize(new java.awt.Dimension(80, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(80, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(80, 23));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        salesManageSales sms = new salesManageSales(modifySalesOrder.row);
        sms.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifySalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifySalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifySalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifySalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifySalesOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JComboBox<String> cbSOID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbSOID;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable orderTable;
    private javax.swing.JSpinner spinQuantity;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
