/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

/**
 *
 * @author User
 */
public class OfficerPanel extends javax.swing.JFrame {

    /**
     * Creates new form OfficerPanel
     */
    public OfficerPanel() {
        initComponents();
    }
    
    public static String[] row;
    
    public OfficerPanel(String[] row){
        initComponents();
        setLocationRelativeTo(null);
        OfficerPanel.row = row;
        System.out.println("Officer Panel: " + row);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btManagePP = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btProcessSO = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btSubmitSales = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btCheckStatus = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btGeneratereport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Officer Panel");
        setMinimumSize(new java.awt.Dimension(663, 569));
        setPreferredSize(new java.awt.Dimension(663, 569));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(663, 75));
        jPanel3.setPreferredSize(new java.awt.Dimension(670, 75));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton6.setText("Logout");
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 30));

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(670, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(670, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(285, 394));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 394));
        jPanel2.setLayout(new java.awt.GridLayout(9, 0));

        btManagePP.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btManagePP.setText("Manage Personal Profile");
        btManagePP.setFocusPainted(false);
        btManagePP.setFocusable(false);
        btManagePP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManagePPActionPerformed(evt);
            }
        });
        jPanel2.add(btManagePP);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        btProcessSO.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btProcessSO.setText("Process Sales Order");
        btProcessSO.setFocusPainted(false);
        btProcessSO.setFocusable(false);
        btProcessSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcessSOActionPerformed(evt);
            }
        });
        jPanel2.add(btProcessSO);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        btSubmitSales.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btSubmitSales.setText("Submit Sales");
        btSubmitSales.setFocusPainted(false);
        btSubmitSales.setFocusable(false);
        btSubmitSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitSalesActionPerformed(evt);
            }
        });
        jPanel2.add(btSubmitSales);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9);

        btCheckStatus.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btCheckStatus.setText("Check Sales Product Status");
        btCheckStatus.setFocusPainted(false);
        btCheckStatus.setFocusable(false);
        btCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckStatusActionPerformed(evt);
            }
        });
        jPanel2.add(btCheckStatus);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10);

        btGeneratereport.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btGeneratereport.setText("Generate Report");
        btGeneratereport.setFocusPainted(false);
        btGeneratereport.setFocusable(false);
        btGeneratereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeneratereportActionPerformed(evt);
            }
        });
        jPanel2.add(btGeneratereport);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btManagePPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManagePPActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        PersonalProfile pp = new PersonalProfile(OfficerPanel.row);
        pp.setVisible(true);
    }//GEN-LAST:event_btManagePPActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btProcessSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcessSOActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        OsearchSalesOrder pso = new OsearchSalesOrder(OfficerPanel.row);
        pso.setVisible(true);
    }//GEN-LAST:event_btProcessSOActionPerformed

    private void btCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckStatusActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SalesOrderStatus sos = new SalesOrderStatus(OfficerPanel.row);
        sos.setVisible(true);
    }//GEN-LAST:event_btCheckStatusActionPerformed

    private void btGeneratereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeneratereportActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        generateReport gr = new generateReport(OfficerPanel.row);
        gr.setVisible(true);
    }//GEN-LAST:event_btGeneratereportActionPerformed

    private void btSubmitSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitSalesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        salesInvoice si = new salesInvoice(OfficerPanel.row);
        si.setVisible(true);
    }//GEN-LAST:event_btSubmitSalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCheckStatus;
    private javax.swing.JButton btGeneratereport;
    private javax.swing.JButton btManagePP;
    private javax.swing.JButton btProcessSO;
    private javax.swing.JButton btSubmitSales;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
